import {
  HistoryIcon as History,
  SearchIcon as Search,
  FlightTakeOffIcon as FlightTakeOff,
  GoodIcon as Good,
  SosoIcon as Soso,
  BestIcon as Best,
  BadIcon as Bad,
  ChaosIcon as Chaos,
  FlyingAirplaneIcon as FlyingAirplane,
  ShareIcon as Share,
  LikeIcon as Like,
  BookmarkIcon as Bookmark,
  BookmarkActiveIcon as BookmarkActive,
  HeartIcon as Heart,
  HeartOutlinedIcon as HeartOutlined,
  HomeIcon as Home,
  PhotoIcon as Photo,
  NavHome,
  NavProfile,
  NavBeer,
  NavTravel,
  NavHomeActive,
  NavProfileActive,
  NavBeerActive,
  NavTravelActive,
  Plus,
  AirplaneIcon as Airplane,
  BackIcon as Back,
  XIcon as X,
  GridViewIcon as GridView,
  ListViewIcon as ListView,
  WriteIcon as Write,
  SaveIcon as Save,
} from '@/assets/icon';

export const svg = {
  History,
  Search,
  FlightTakeOff,
  Good,
  Soso,
  Best,
  Bad,
  Chaos,
  FlyingAirplane,
  Share,
  Like,
  Bookmark,
  BookmarkActive,
  Heart,
  HeartOutlined,
  Home,
  Photo,
  NavHome,
  NavProfile,
  NavBeer,
  NavTravel,
  NavHomeActive,
  NavProfileActive,
  NavBeerActive,
  NavTravelActive,
  Plus,
  Airplane,
  Back,
  X,
  GridView,
  ListView,
  Write,
  Save,
};
