import {
  ArrowDownIcon as ArrowDown,
  CheckIcon as Check,
  HistoryIcon as History,
  SearchIcon as Search,
  FlightTakeOffIcon as FlightTakeOff,
  GoodIcon as Good,
  SosoIcon as Soso,
  BestIcon as Best,
  BadIcon as Bad,
  Barcode,
  ChaosIcon as Chaos,
  FilterIcon as Filter,
  FilterAppliedIcon as FilterApplied,
  FlyingAirplaneIcon as FlyingAirplane,
  ShareIcon as Share,
  LikeIcon as Like,
  HeartIcon as Heart,
  HeartOutlinedIcon as HeartOutlined,
  HomeIcon as Home,
  PhotoIcon as Photo,
  NavHome,
  NavProfile,
  NavBeer,
  NavTravel,
  NavHomeActive,
  NavProfileActive,
  NavBeerActive,
  NavTravelActive,
  Plus,
  AirplaneIcon as Airplane,
  RandomIcon as Random,
  BackIcon as Back,
  XIcon as X,
  XCircleIcon as XCircle,
  GridViewIcon as GridView,
  ListViewIcon as ListView,
  WriteIcon as Write,
  SaveIcon as Save,
  CloseIcon as Close,
  NextIcon as Next,
  PlusCircleIcon as PlusCircle,
  ThreeDotIcon as ThreeDot,
  ConveyorBelt,
  ArrowLeftIcon as ArrowLeft,
  ArrowRightIcon as ArrowRight,
  Level1Icon as Level1,
  Level2Icon as Level2,
  Level3Icon as Level3,
  Level4Icon as Level4,
  Level5Icon as Level5,
  ModifyIcon as Modify,
  InfoIcon as Info,
  Logo,
  WorldIcon as World,
  Stamp1Icon as Stamp1,
  Stamp2Icon as Stamp2,
  Stamp3Icon as Stamp3,
  Stamp4Icon as Stamp4,
  Stamp5Icon as Stamp5,
  Cloud,
  Naver,
} from '@/assets/icon';

export const svg = {
  ArrowDown,
  Check,
  History,
  Search,
  FlightTakeOff,
  Good,
  Soso,
  Best,
  Bad,
  Barcode,
  Chaos,
  Filter,
  FilterApplied,
  FlyingAirplane,
  Share,
  Like,
  Heart,
  HeartOutlined,
  Home,
  Photo,
  NavHome,
  NavProfile,
  NavBeer,
  NavTravel,
  NavHomeActive,
  NavProfileActive,
  NavBeerActive,
  NavTravelActive,
  Plus,
  Airplane,
  Random,
  Back,
  X,
  XCircle,
  GridView,
  ListView,
  Write,
  Save,
  Close,
  Next,
  PlusCircle,
  ThreeDot,
  ConveyorBelt,
  ArrowLeft,
  ArrowRight,
  Level1,
  Level2,
  Level3,
  Level4,
  Level5,
  Modify,
  Info,
  Logo,
  World,
  Stamp1,
  Stamp2,
  Stamp3,
  Stamp4,
  Stamp5,
  Cloud,
  Naver,
};
