import { EBeerType, IBeer } from '@/apis';

export const Beers: IBeer[] = [
  {
    id: 1,
    country: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    type: {
      nameEng: EBeerType.LIGHT_ALE,
      nameKor: '위트 에일',
      imageUrl: '',
      description: '투명한 황금빛으로 단 맛과 쓴 맛이 어우러진 깔끔한 맛',
    },
    startCountry: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    endCountry: {
      id: 1,
      nameKor: '미국',
      nameEng: 'usa',
      imageUrl: '',
      continent: {
        id: 2,
        name: '아메리카',
      },
    },
    nameKor: '제주 위트 에일 제주 위트 에일 제주 위트 에일 제주 위트 에일',
    nameEng: 'Jeju Wit Ale Jeju Wit Ale Jeju Wit Ale Jeju Wit Ale Jeju Wit Ale Jeju Wit Ale',
    imageUrl: 'https://ifh.cc/g/X6B8Ra.png',
    content:
      '‘제주 위트 에일’은 제주 청정 재료인 유기농 제주 감귤 껍질을 사용해 은은한 감귤 향의 산뜻한 끝 맛이 특징이다. 독일산 보리 맥아와 밀 맥아를 함께 사용해 부드러운 음용감으로 에일 맥주 입문자들도 편하게 즐길 수 있다.',
    alcohol: 5.5,
    price: 4200,
    volume: 50,
    feel: 4,
    isLiked: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    country: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    type: {
      nameEng: EBeerType.LIGHT_ALE,
      nameKor: '위트 에일',
      imageUrl: '',
      description: '투명한 황금빛으로 단 맛과 쓴 맛이 어우러진 깔끔한 맛',
    },
    startCountry: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    endCountry: {
      id: 1,
      nameKor: '미국',
      nameEng: 'usa',
      imageUrl: '',
      continent: {
        id: 2,
        name: '아메리카',
      },
    },
    nameKor: '제주 위트 에일',
    nameEng: 'Jeju Wit Ale',
    imageUrl: 'https://ifh.cc/g/X6B8Ra.png',
    content:
      '‘제주 위트 에일’은 제주 청정 재료인 유기농 제주 감귤 껍질을 사용해 은은한 감귤 향의 산뜻한 끝 맛이 특징이다. 독일산 보리 맥아와 밀 맥아를 함께 사용해 부드러운 음용감으로 에일 맥주 입문자들도 편하게 즐길 수 있다.',
    alcohol: 5.5,
    price: 4200,
    volume: 50,
    feel: null,
    isLiked: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 3,
    country: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    type: {
      nameEng: EBeerType.LIGHT_ALE,
      nameKor: '위트 에일',
      imageUrl: '',
      description: '투명한 황금빛으로 단 맛과 쓴 맛이 어우러진 깔끔한 맛',
    },
    startCountry: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    endCountry: {
      id: 1,
      nameKor: '미국',
      nameEng: 'usa',
      imageUrl: '',
      continent: {
        id: 2,
        name: '아메리카',
      },
    },
    nameKor: '제주 위트 에일',
    nameEng: 'Jeju Wit Ale',
    imageUrl: 'https://ifh.cc/g/X6B8Ra.png',
    content:
      '‘제주 위트 에일’은 제주 청정 재료인 유기농 제주 감귤 껍질을 사용해 은은한 감귤 향의 산뜻한 끝 맛이 특징이다. 독일산 보리 맥아와 밀 맥아를 함께 사용해 부드러운 음용감으로 에일 맥주 입문자들도 편하게 즐길 수 있다.',
    alcohol: 5.5,
    price: 4200,
    volume: 50,
    feel: 2,
    isLiked: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    country: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    type: {
      nameEng: EBeerType.LIGHT_ALE,
      nameKor: '위트 에일',
      imageUrl: '',
      description: '투명한 황금빛으로 단 맛과 쓴 맛이 어우러진 깔끔한 맛',
    },
    startCountry: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    endCountry: {
      id: 1,
      nameKor: '미국',
      nameEng: 'usa',
      imageUrl: '',
      continent: {
        id: 2,
        name: '아메리카',
      },
    },
    nameKor: '제주 위트 에일',
    nameEng: 'Jeju Wit Ale',
    imageUrl: 'https://ifh.cc/g/X6B8Ra.png',
    content:
      '‘제주 위트 에일’은 제주 청정 재료인 유기농 제주 감귤 껍질을 사용해 은은한 감귤 향의 산뜻한 끝 맛이 특징이다. 독일산 보리 맥아와 밀 맥아를 함께 사용해 부드러운 음용감으로 에일 맥주 입문자들도 편하게 즐길 수 있다.',
    alcohol: 5.5,
    price: 4200,
    volume: 50,
    feel: 1,
    isLiked: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    country: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    type: {
      nameEng: EBeerType.LIGHT_ALE,
      nameKor: '위트 에일',
      imageUrl: '',
      description: '투명한 황금빛으로 단 맛과 쓴 맛이 어우러진 깔끔한 맛',
    },
    startCountry: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    endCountry: {
      id: 1,
      nameKor: '미국',
      nameEng: 'usa',
      imageUrl: '',
      continent: {
        id: 2,
        name: '아메리카',
      },
    },
    nameKor: '제주 위트 에일',
    nameEng: 'Jeju Wit Ale',
    imageUrl: 'https://ifh.cc/g/X6B8Ra.png',
    content:
      '‘제주 위트 에일’은 제주 청정 재료인 유기농 제주 감귤 껍질을 사용해 은은한 감귤 향의 산뜻한 끝 맛이 특징이다. 독일산 보리 맥아와 밀 맥아를 함께 사용해 부드러운 음용감으로 에일 맥주 입문자들도 편하게 즐길 수 있다.',
    alcohol: 5.5,
    price: 4200,
    volume: 50,
    feel: 5,
    isLiked: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    country: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    type: {
      nameEng: EBeerType.LIGHT_ALE,
      nameKor: '위트 에일',
      imageUrl: '',
      description: '투명한 황금빛으로 단 맛과 쓴 맛이 어우러진 깔끔한 맛',
    },
    startCountry: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    endCountry: {
      id: 1,
      nameKor: '미국',
      nameEng: 'usa',
      imageUrl: '',
      continent: {
        id: 2,
        name: '아메리카',
      },
    },
    nameKor: '제주 위트 에일',
    nameEng: 'Jeju Wit Ale',
    imageUrl: 'https://ifh.cc/g/X6B8Ra.png',
    content:
      '‘제주 위트 에일’은 제주 청정 재료인 유기농 제주 감귤 껍질을 사용해 은은한 감귤 향의 산뜻한 끝 맛이 특징이다. 독일산 보리 맥아와 밀 맥아를 함께 사용해 부드러운 음용감으로 에일 맥주 입문자들도 편하게 즐길 수 있다.',
    alcohol: 5.5,
    price: 4200,
    volume: 50,
    feel: null,
    isLiked: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    country: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    type: {
      nameEng: EBeerType.LIGHT_ALE,
      nameKor: '위트 에일',
      imageUrl: '',
      description: '투명한 황금빛으로 단 맛과 쓴 맛이 어우러진 깔끔한 맛',
    },
    startCountry: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    endCountry: {
      id: 1,
      nameKor: '미국',
      nameEng: 'usa',
      imageUrl: '',
      continent: {
        id: 2,
        name: '아메리카',
      },
    },
    nameKor: '제주 위트 에일',
    nameEng: 'Jeju Wit Ale',
    imageUrl: 'https://ifh.cc/g/X6B8Ra.png',
    content:
      '‘제주 위트 에일’은 제주 청정 재료인 유기농 제주 감귤 껍질을 사용해 은은한 감귤 향의 산뜻한 끝 맛이 특징이다. 독일산 보리 맥아와 밀 맥아를 함께 사용해 부드러운 음용감으로 에일 맥주 입문자들도 편하게 즐길 수 있다.',
    alcohol: 5.5,
    price: 4200,
    volume: 50,
    feel: 5,
    isLiked: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    country: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    type: {
      nameEng: EBeerType.LIGHT_ALE,
      nameKor: '위트 에일',
      imageUrl: '',
      description: '투명한 황금빛으로 단 맛과 쓴 맛이 어우러진 깔끔한 맛',
    },
    startCountry: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    endCountry: {
      id: 1,
      nameKor: '미국',
      nameEng: 'usa',
      imageUrl: '',
      continent: {
        id: 2,
        name: '아메리카',
      },
    },
    nameKor: '제주 위트 에일',
    nameEng: 'Jeju Wit Ale',
    imageUrl: 'https://ifh.cc/g/X6B8Ra.png',
    content:
      '‘제주 위트 에일’은 제주 청정 재료인 유기농 제주 감귤 껍질을 사용해 은은한 감귤 향의 산뜻한 끝 맛이 특징이다. 독일산 보리 맥아와 밀 맥아를 함께 사용해 부드러운 음용감으로 에일 맥주 입문자들도 편하게 즐길 수 있다.',
    alcohol: 5.5,
    price: 4200,
    volume: 50,
    feel: 5,
    isLiked: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9,
    country: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    type: {
      nameEng: EBeerType.LIGHT_ALE,
      nameKor: '위트 에일',
      imageUrl: '',
      description: '투명한 황금빛으로 단 맛과 쓴 맛이 어우러진 깔끔한 맛',
    },
    startCountry: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    endCountry: {
      id: 1,
      nameKor: '미국',
      nameEng: 'usa',
      imageUrl: '',
      continent: {
        id: 2,
        name: '아메리카',
      },
    },
    nameKor: '제주 위트 에일',
    nameEng: 'Jeju Wit Ale',
    imageUrl: 'https://ifh.cc/g/X6B8Ra.png',
    content:
      '‘제주 위트 에일’은 제주 청정 재료인 유기농 제주 감귤 껍질을 사용해 은은한 감귤 향의 산뜻한 끝 맛이 특징이다. 독일산 보리 맥아와 밀 맥아를 함께 사용해 부드러운 음용감으로 에일 맥주 입문자들도 편하게 즐길 수 있다.',
    alcohol: 5.5,
    price: 4200,
    volume: 50,
    feel: 5,
    isLiked: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 10,
    country: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    type: {
      nameEng: EBeerType.LIGHT_ALE,
      nameKor: '위트 에일',
      imageUrl: '',
      description: '투명한 황금빛으로 단 맛과 쓴 맛이 어우러진 깔끔한 맛',
    },
    startCountry: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    endCountry: {
      id: 1,
      nameKor: '미국',
      nameEng: 'usa',
      imageUrl: '',
      continent: {
        id: 2,
        name: '아메리카',
      },
    },
    nameKor: '제주 위트 에일',
    nameEng: 'Jeju Wit Ale',
    imageUrl: 'https://ifh.cc/g/X6B8Ra.png',
    content:
      '‘제주 위트 에일’은 제주 청정 재료인 유기농 제주 감귤 껍질을 사용해 은은한 감귤 향의 산뜻한 끝 맛이 특징이다. 독일산 보리 맥아와 밀 맥아를 함께 사용해 부드러운 음용감으로 에일 맥주 입문자들도 편하게 즐길 수 있다.',
    alcohol: 5.5,
    price: 4200,
    volume: 50,
    feel: 5,
    isLiked: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 11,
    country: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    type: {
      nameEng: EBeerType.LIGHT_ALE,
      nameKor: '위트 에일',
      imageUrl: '',
      description: '투명한 황금빛으로 단 맛과 쓴 맛이 어우러진 깔끔한 맛',
    },
    startCountry: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    endCountry: {
      id: 1,
      nameKor: '미국',
      nameEng: 'usa',
      imageUrl: '',
      continent: {
        id: 2,
        name: '아메리카',
      },
    },
    nameKor: '제주 위트 에일',
    nameEng: 'Jeju Wit Ale',
    imageUrl: 'https://ifh.cc/g/X6B8Ra.png',
    content:
      '‘제주 위트 에일’은 제주 청정 재료인 유기농 제주 감귤 껍질을 사용해 은은한 감귤 향의 산뜻한 끝 맛이 특징이다. 독일산 보리 맥아와 밀 맥아를 함께 사용해 부드러운 음용감으로 에일 맥주 입문자들도 편하게 즐길 수 있다.',
    alcohol: 5.5,
    price: 4200,
    volume: 50,
    feel: 5,
    isLiked: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 12,
    country: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    type: {
      nameEng: EBeerType.LIGHT_ALE,
      nameKor: '위트 에일',
      imageUrl: '',
      description: '투명한 황금빛으로 단 맛과 쓴 맛이 어우러진 깔끔한 맛',
    },
    startCountry: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    endCountry: {
      id: 1,
      nameKor: '미국',
      nameEng: 'usa',
      imageUrl: '',
      continent: {
        id: 2,
        name: '아메리카',
      },
    },
    nameKor: '제주 위트 에일',
    nameEng: 'Jeju Wit Ale',
    imageUrl: 'https://ifh.cc/g/X6B8Ra.png',
    content:
      '‘제주 위트 에일’은 제주 청정 재료인 유기농 제주 감귤 껍질을 사용해 은은한 감귤 향의 산뜻한 끝 맛이 특징이다. 독일산 보리 맥아와 밀 맥아를 함께 사용해 부드러운 음용감으로 에일 맥주 입문자들도 편하게 즐길 수 있다.',
    alcohol: 5.5,
    price: 4200,
    volume: 50,
    feel: 5,
    isLiked: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 13,
    country: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    type: {
      nameEng: EBeerType.LIGHT_ALE,
      nameKor: '위트 에일',
      imageUrl: '',
      description: '투명한 황금빛으로 단 맛과 쓴 맛이 어우러진 깔끔한 맛',
    },
    startCountry: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    endCountry: {
      id: 1,
      nameKor: '미국',
      nameEng: 'usa',
      imageUrl: '',
      continent: {
        id: 2,
        name: '아메리카',
      },
    },
    nameKor: '제주 위트 에일',
    nameEng: 'Jeju Wit Ale',
    imageUrl: 'https://ifh.cc/g/X6B8Ra.png',
    content:
      '‘제주 위트 에일’은 제주 청정 재료인 유기농 제주 감귤 껍질을 사용해 은은한 감귤 향의 산뜻한 끝 맛이 특징이다. 독일산 보리 맥아와 밀 맥아를 함께 사용해 부드러운 음용감으로 에일 맥주 입문자들도 편하게 즐길 수 있다.',
    alcohol: 5.5,
    price: 4200,
    volume: 50,
    feel: 5,
    isLiked: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 14,
    country: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    type: {
      nameEng: EBeerType.LIGHT_ALE,
      nameKor: '위트 에일',
      imageUrl: '',
      description: '투명한 황금빛으로 단 맛과 쓴 맛이 어우러진 깔끔한 맛',
    },
    startCountry: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    endCountry: {
      id: 1,
      nameKor: '미국',
      nameEng: 'usa',
      imageUrl: '',
      continent: {
        id: 2,
        name: '아메리카',
      },
    },
    nameKor: '제주 위트 에일',
    nameEng: 'Jeju Wit Ale',
    imageUrl: 'https://ifh.cc/g/X6B8Ra.png',
    content:
      '‘제주 위트 에일’은 제주 청정 재료인 유기농 제주 감귤 껍질을 사용해 은은한 감귤 향의 산뜻한 끝 맛이 특징이다. 독일산 보리 맥아와 밀 맥아를 함께 사용해 부드러운 음용감으로 에일 맥주 입문자들도 편하게 즐길 수 있다.',
    alcohol: 5.5,
    price: 4200,
    volume: 50,
    feel: 5,
    isLiked: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 15,
    country: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    type: {
      nameEng: EBeerType.LIGHT_ALE,
      nameKor: '위트 에일',
      imageUrl: '',
      description: '투명한 황금빛으로 단 맛과 쓴 맛이 어우러진 깔끔한 맛',
    },
    startCountry: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    endCountry: {
      id: 1,
      nameKor: '미국',
      nameEng: 'usa',
      imageUrl: '',
      continent: {
        id: 2,
        name: '아메리카',
      },
    },
    nameKor: '제주 위트 에일',
    nameEng: 'Jeju Wit Ale',
    imageUrl: 'https://ifh.cc/g/X6B8Ra.png',
    content:
      '‘제주 위트 에일’은 제주 청정 재료인 유기농 제주 감귤 껍질을 사용해 은은한 감귤 향의 산뜻한 끝 맛이 특징이다. 독일산 보리 맥아와 밀 맥아를 함께 사용해 부드러운 음용감으로 에일 맥주 입문자들도 편하게 즐길 수 있다.',
    alcohol: 5.5,
    price: 4200,
    volume: 50,
    feel: 5,
    isLiked: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 16,
    country: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    type: {
      nameEng: EBeerType.LIGHT_ALE,
      nameKor: '위트 에일',
      imageUrl: '',
      description: '투명한 황금빛으로 단 맛과 쓴 맛이 어우러진 깔끔한 맛',
    },
    startCountry: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    endCountry: {
      id: 1,
      nameKor: '미국',
      nameEng: 'usa',
      imageUrl: '',
      continent: {
        id: 2,
        name: '아메리카',
      },
    },
    nameKor: '제주 위트 에일',
    nameEng: 'Jeju Wit Ale',
    imageUrl: 'https://ifh.cc/g/X6B8Ra.png',
    content:
      '‘제주 위트 에일’은 제주 청정 재료인 유기농 제주 감귤 껍질을 사용해 은은한 감귤 향의 산뜻한 끝 맛이 특징이다. 독일산 보리 맥아와 밀 맥아를 함께 사용해 부드러운 음용감으로 에일 맥주 입문자들도 편하게 즐길 수 있다.',
    alcohol: 5.5,
    price: 4200,
    volume: 50,
    feel: 5,
    isLiked: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 17,
    country: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    type: {
      nameEng: EBeerType.LIGHT_ALE,
      nameKor: '위트 에일',
      imageUrl: '',
      description: '투명한 황금빛으로 단 맛과 쓴 맛이 어우러진 깔끔한 맛',
    },
    startCountry: {
      id: 1,
      nameKor: '한국',
      nameEng: 'korea',
      imageUrl: '',
      continent: {
        id: 1,
        name: '아시아',
      },
    },
    endCountry: {
      id: 1,
      nameKor: '미국',
      nameEng: 'usa',
      imageUrl: '',
      continent: {
        id: 2,
        name: '아메리카',
      },
    },
    nameKor: '제주 위트 에일',
    nameEng: 'Jeju Wit Ale',
    imageUrl: 'https://ifh.cc/g/X6B8Ra.png',
    content:
      '‘제주 위트 에일’은 제주 청정 재료인 유기농 제주 감귤 껍질을 사용해 은은한 감귤 향의 산뜻한 끝 맛이 특징이다. 독일산 보리 맥아와 밀 맥아를 함께 사용해 부드러운 음용감으로 에일 맥주 입문자들도 편하게 즐길 수 있다.',
    alcohol: 5.5,
    price: 4200,
    volume: 50,
    feel: 5,
    isLiked: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
